### ISSUE TITLE
Feature request: Aspect ratio 1:1

### ISSUE THREAD

**Issue by Gnarflord** [LionyxML/rx-plotter#1]
I'd like to have an option so the aspect ratio is fixed to 1:1. As I understand it the current code simply scales the y-axis to the maximum and minimum values but this kinda breaks when plotting something like tan(x).
In matplot this can be done with
`    axis.set_aspect("equal")
`

**Comment by LionyxML** [comment]
Now you can zoom Y, and set X to what you with, so, it`s kind of what you wanted :)
